name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Create plugin directory
      run: |
        mkdir -p dniwoo
        rsync -av --exclude='.git' --exclude='.github' --exclude='vendor' --exclude='node_modules' --exclude='*.md' --exclude='composer.*' --exclude='install.*' . dniwoo/
    
    - name: Create ZIP
      run: |
        zip -r dniwoo-${{ steps.get_version.outputs.VERSION }}.zip dniwoo/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dniwoo-${{ steps.get_version.outputs.VERSION }}.zip
        name: DNIWOO v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## DNIWOO v${{ steps.get_version.outputs.VERSION }}
          
          Professional DNI/NIF field for WooCommerce checkout.
          
          ### Installation
          1. Download the ZIP file below
          2. Upload to WordPress via Plugins > Add New > Upload Plugin
          3. Activate the plugin
          
          ### Changes
          See CHANGELOG.md for details.
          
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
